# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: nuget_prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Package Nuget 📦
      run: |
        dotnet build -c Release "EasyTool.Core/EasyTool.Core.csproj"
        SUFFIX=`date "+%y%m%d%H%M%S"`
        dotnet pack "EasyTool.Core/EasyTool.Core.csproj" /p:PackageVersion=$VERSION -c Release -o publish --no-build --no-restore
    - name: Publish to Nuget ✔
      run: |
        dotnet nuget push publish/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
